name: Build executables (All platform)

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      postfix:
        required: true
        type: string

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true    

jobs:
  build_windows:
    if: ${{ inputs.os == 'windows' }}
    runs-on: windows-latest
    # needs: 
    #   - test_heavy_windows
    env:
      MACHINE_OS: windows
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: 'stable'
      - name: Doctor
        run: flutter doctor -v
      - name: Install Dependencies
        run: |
          flutter config --enable-windows-desktop	
          flutter packages get
      - name: Build release
        run: |	
          flutter build -v ${{ env.MACHINE_OS }} --release	
      - name: Copy essentials to Windows artifacs (Release)
        run: |
          cp -Path ${{ github.workspace }}/build_dependencies/windows/* ${{ github.workspace }}/build/windows/runner/Release/
          mkdir ${{ github.workspace }}/build/windows/runner/subtitle_wand/subtitle_wand
          mv -Path ${{ github.workspace }}/build/windows/runner/Release/* ${{ github.workspace }}/build/windows/runner/subtitle_wand/subtitle_wand
      - name: Upload Windows artifaces (Release)
        uses: actions/upload-artifact@v3
        with:
          name: windows-release-${{ github.sha }}
          path: ${{ github.workspace }}/build/windows/runner/subtitle_wand
  build_ubuntu:
    if: ${{ inputs.os == 'linux' }}
    runs-on: ubuntu-latest
    # needs: 
    #   - test_heavy_ubuntu
    env:
      MACHINE_OS: linux
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: 'stable'
      - name: Install Linux dependencies	
        # if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev liblzma-dev
      - name: Doctor
        run: flutter doctor -v
      - name: Install Dependencies
        run: |
          flutter config --enable-linux-desktop	
          flutter packages get
      - name: Build release
        run: |	
          flutter build -v ${{ env.MACHINE_OS }} --release	
      - name: Copy essentials to Linux artifacs and package (Release)
        run: |
          cp -r ${{ github.workspace }}/build_dependencies/linux ${{ github.workspace }}/build/linux/x64/release/subtitle_wand
          mv ${{ github.workspace }}/build/linux/x64/release/bundle/* ${{ github.workspace }}/build/linux/x64/release/subtitle_wand/usr/local/lib/subtitle_wand/
          dpkg-deb --build --root-owner-group ${{ github.workspace }}/build/linux/x64/release/subtitle_wand
      - name: Upload Linux artifaces (Release)
        uses: actions/upload-artifact@v3
        with:
          name: linux-release-${{ github.sha }}
          path: ${{ github.workspace }}/build/linux/x64/release/subtitle_wand.deb
  build_macos:
    if: ${{ inputs.os == 'macos' }}
    runs-on: macos-latest
    # needs: 
    #   - test_heavy_macos
    env:
      MACHINE_OS: macos
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: 'stable'
      - name: Doctor
        run: flutter doctor -v
      - name: Install Dependencies
        run: |
          flutter config --enable-macos-desktop	
          flutter packages get
      - name: Build release
        run: |	
          flutter build -v ${{ env.MACHINE_OS }} --release	
      - name: Copy essentials to Macos and package (Release)
        run: |
          mkdir ${{ github.workspace }}/build/macos/Build/Products/subtitle_wand
          mv ${{ github.workspace }}/build/macos/Build/Products/Release/subtitle_wand.app ${{ github.workspace }}/build/macos/Build/Products/subtitle_wand/subtitle_wand.app
      - name: Upload MacOS artifaces (Release)
        # if: startsWith(matrix.os, 'macOS')
        uses: actions/upload-artifact@v3
        with:
          name: macos-release-${{ github.sha }}
          path: ${{ github.workspace }}/build/macos/Build/Products/subtitle_wand