name: build

on:
  push:
    paths:
    - '.github/workflows/main.yaml'
    - 'test/**'
    - 'lib/**'
    - 'resources/**'
    - 'windows/**'
    - 'macos/**'
    - 'linux/**'
    - 'go/**'
    - 'fonts/**'
    - 'scripts/**'

  pull_request:
    paths:
    - 'test/**'
    - 'lib/**'
    - 'resources/**'
    - 'windows/**'
    - 'macos/**'
    - 'linux/**'
    - 'go/**'
    - 'fonts/**'

env:
  flutter_channel: 'stable'
  flutter_version: '1.12.13+hotfix.8'

jobs:
  # Analyze and test each core package.
  commit-review:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        folder: ['.']
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            flutter_path: /opt/hostedtoolcache/flutter
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.OS }}-flutter-cache-${{ env.flutter_version }}
          restore-keys: |
            ${{ runner.OS }}-flutter-cache-

      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}

      - name: Analyze and test
        env:
          FLUTTER_DART_HOME: ${{ env.FLUTTER_HOME }}/bin/cache/dart-sdk/bin
        run: |
          export PATH=$PATH:$FLUTTER_DART_HOME
          ./scripts/ci.sh ${{ matrix.folder }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ${{ matrix.folder }}/coverage/lcov.info