name: Test

on:
  watch:
    types: [started]

env:
  flutter_channel: 'stable'
  flutter_version: '1.12.13+hotfix.8'

jobs:
  # Analyze and test each core package.
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        folder: ['.']
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            flutter_path: /opt/hostedtoolcache/flutter
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.OS }}-flutter-cache-${{ env.flutter_version }}
          restore-keys: |
            ${{ runner.OS }}-flutter-cache-

      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}
      - uses: actions/setup-go@v2-beta
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.
      - run: |
          go version
          go get -u github.com/go-flutter-desktop/hover
          apt-get install -y gcc libc6-dev libgl1-mesa-dev xorg-dev

      - name: Build exectuables
        env:
          FLUTTER_DART_HOME: ${{ env.FLUTTER_HOME }}/bin/cache/dart-sdk/bin
        run: |
          export PATH=$PATH:$FLUTTER_DART_HOME
          hover build linux
                - name: Upload math result for job 1
      - uses: actions/upload-artifact@v1
        with:
          name: homework
          path: go/build/outputs