name: Test (All platform)

on: 
  push:
    branches:
      - 'main'
      - 'releases-**'
    paths:
      - '.github/workflows/build.yml'
      - '.github/workflows/build_**.yml'
      - '.github/workflows/test.yml'
      - 'build_dependencies/**'
      - 'fonts/**'
      - 'lib/**'
      - 'macos/**'
      - 'linux/**'
      - 'windows/**'
      - 'packages/**'
      - 'test/**'
      - 'analysis_options.yaml'
      - 'test.yaml'
      - 'build.yaml'
      - 'dart_test.yaml'
      - 'pubspec.yaml'
    # paths-ignore:
    #   - '**/README.md'
    #   - '**/README.md'
  pull_request:
    types:
      - opened
    branches:
      - 'main'
    paths:
      - '.github/workflows/build.yml'
      - 'build_dependencies/**'
      - 'fonts/**'
      - 'lib/**'
      - 'macos/**'
      - 'linux/**'
      - 'windows/**'
      - 'packages/**'
      - 'test/**'
      - 'analysis_options.yaml'
      - 'build.yaml'
      - 'dart_test.yaml'
      - 'pubspec.yaml'

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: 'stable'
      - name: Install Dependencies
        run: |
          flutter packages get
      - name: Lint and Format
        run: |
          flutter pub run melos run lint:all
  test_windows:
    env:
      MACHINE_OS: windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: 'stable'
      - name: Install Dependencies
        run: |
          flutter packages get
      - name: Unit test
        run: |
          flutter pub run melos test --no-select
  test_ubuntu:
    env:
      MACHINE_OS: linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: 'stable'
      - name: Install Dependencies
        run: |
          flutter packages get
      - name: Unit test
        run: |
          flutter pub run melos test --no-select
  test_macos:
    env:
      MACHINE_OS: macos
    runs-on: macos-latest
    steps:
      - name: Test (TODO removed)
        run : |
          top -l 1 -s 0 | grep PhysMem | awk '{print $2}'
          top -l 1 -s 0 | grep PhysMem | awk '{print $6}'
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: 'stable'
      - name: Install Dependencies
        run: |
          flutter packages get
      - name: Unit test
        run: |
          flutter pub run melos test --no-select
  test_heavy_windows:
    needs: 
      - test_windows
    env:
      MACHINE_OS: windows
    runs-on: windows-latest
    steps:
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: 'stable'
      - name: Install Dependencies
        run: |
          flutter packages get
      - name: Integration test
        run: |
          flutter pub run melos test:integration --no-select
  test_heavy_ubuntu:
    needs: 
      - test_ubuntu
    env:
      MACHINE_OS: linux
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: 'stable'
      - name: Install Dependencies
        run: |
          flutter packages get
      - name: Integration test
        run: |
          flutter pub run melos test:integration --no-select
  test_heavy_macos:
    needs: 
      - test_macos
    env:
      MACHINE_OS: macos
    runs-on: macos-latest
    steps:
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: 'stable'
      - name: Install Dependencies
        run: |
          flutter packages get
      - name: Integration test
        run: |
          flutter pub run melos test:integration --no-select
  build_windows:
    needs: 
      - test_heavy_windows
    uses: ./.github/workflows/build_windows.yml
    with: 
      postfix: ${{ github.sha }}
  build_ubuntu:
    needs: 
      - test_heavy_ubuntu
    uses: ./.github/workflows/build_linux.yml
    with: 
      postfix: ${{ github.sha }}
  build_macos:
    needs: 
      - test_heavy_macos
    uses: ./.github/workflows/build_macos.yml
    with: 
      postfix: ${{ github.sha }}